### ISSUE TITLE
Dependency is fails to load in Plugin Application

### ISSUE THREAD

**Issue by MohankumarD** [ralemy/pf4j-spring-tutorial#2]
Successfully we can load external Spring Boot JAR as a plugin in the main Spring Boot application. But plugin jar its fails to load its dependency (not able to load dependency(external Jar here I am using simple-json of plugin application). Deployment as JAR plugin.

Also added dependency in assambly.xml file 
           
```
           <includes>
                <include>org.pf4j:*</include>
                <include>com.googlecode.json-simple:*</include>
            </includes>
```

java.lang.NoClassDefFoundError: org/json/simple/JSONObject
        at com.qruizemagic.springplugin.PluginController.greetMVC(PluginController.java:22) ~[na:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_91]
        at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:139) ~[spring-webflux-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]

**Comment by MohankumarD** [comment]
When I use plugin application as ZIP file, its working fine. Help me on JAR
